"""add gender to provider

Revision ID: 0eb4181b6d48
Revises: a6bcffae1e43
Create Date: 2018-02-05 18:08:39.862861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eb4181b6d48'
down_revision = 'a6bcffae1e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('gender', sa.String(length=32), nullable=True), schema='monday')
    op.create_index(op.f('ix_monday_provider_gender'), 'provider', ['gender'], unique=False, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monday_provider_gender'), table_name='provider', schema='monday')
    op.drop_column('provider', 'gender', schema='monday')
    # ### end Alembic commands ###
