"""add degrees

Revision ID: 1074a877e0b6
Revises: 4583e188bc05
Create Date: 2017-12-30 18:13:25.636975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1074a877e0b6'
down_revision = '4583e188bc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('acronym', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('associate', 'bachelor', 'master', 'doctor', name='educationlevel'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('name', 'level'),
    schema='monday'
    )
    op.create_table('providers_degrees',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['monday.degree.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'degree_id'),
    schema='monday'
    )
    op.add_column('credential', sa.Column('acronym', sa.String(length=16), nullable=True), schema='monday')
    op.alter_column('credential', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               schema='monday')
    op.create_unique_constraint(None, 'credential', ['name'], schema='monday')
    op.add_column('language', sa.Column('native', sa.Boolean(), nullable=True), schema='monday')
    op.drop_index('ix_monday_license_number_licensor_id_licensee_id', table_name='license', schema='monday')
    op.create_unique_constraint(None, 'license', ['number', 'licensor_id', 'licensee_id'], schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'license', schema='monday', type_='unique')
    op.create_index('ix_monday_license_number_licensor_id_licensee_id', 'license', ['number', 'licensor_id', 'licensee_id'], unique=True, schema='monday')
    op.drop_column('language', 'native', schema='monday')
    op.drop_constraint(None, 'credential', schema='monday', type_='unique')
    op.alter_column('credential', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               schema='monday')
    op.drop_column('credential', 'acronym', schema='monday')
    op.drop_table('providers_degrees', schema='monday')
    op.drop_table('degree', schema='monday')
    # ### end Alembic commands ###
