"""more correct unique constraints on degrees

Revision ID: 1ba18066fafe
Revises: 1074a877e0b6
Create Date: 2017-12-30 18:43:20.285837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba18066fafe'
down_revision = '1074a877e0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('degree_name_level_key', 'degree', schema='monday', type_='unique')
    op.create_unique_constraint(None, 'degree', ['acronym', 'level'], schema='monday')
    op.create_unique_constraint(None, 'degree', ['acronym', 'name'], schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'degree', schema='monday', type_='unique')
    op.drop_constraint(None, 'degree', schema='monday', type_='unique')
    op.create_unique_constraint('degree_name_level_key', 'degree', ['name', 'level'], schema='monday')
    # ### end Alembic commands ###
