"""add a tsvector for provider name

Revision ID: 1cf2ee2dd2b0
Revises: 506251026f12
Create Date: 2018-01-06 16:25:12.360334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cf2ee2dd2b0'
down_revision = '506251026f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('name_tsv', postgresql.TSVECTOR(), nullable=True), schema='monday')
    op.create_index('ix_monday_provider_name_gin', 'provider', ['name_tsv'], unique=False, schema='monday', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monday_provider_name_gin', table_name='provider', schema='monday')
    op.drop_column('provider', 'name_tsv', schema='monday')
    # ### end Alembic commands ###
