"""tgram index

Revision ID: 2bbd0a48c95d
Revises: ae597ce87450
Create Date: 2018-04-02 14:05:32.703725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bbd0a48c95d'
down_revision = 'ae597ce87450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_monday_provider_first_name_last_name_gin', 'provider', ['first_name', 'last_name'], unique=False, schema='monday', postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops', 'last_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monday_provider_first_name_last_name_gin', table_name='provider', schema='monday')
    # ### end Alembic commands ###
