"""add phone index

Revision ID: 36c2147fa772
Revises: cdcfceb14354
Create Date: 2017-12-28 12:53:02.655678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c2147fa772'
down_revision = 'cdcfceb14354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_monday_phone_npa_nxx_xxxx_extension', 'phone', ['npa', 'nxx', 'xxxx', 'extension'], unique=True, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monday_phone_npa_nxx_xxxx_extension', table_name='phone', schema='monday')
    # ### end Alembic commands ###
