"""initial generation of the db

Revision ID: 4583e188bc05
Revises: 
Create Date: 2017-12-30 12:11:52.464562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4583e188bc05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS monday")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.String(), nullable=True),
    sa.Column('geocoding_api_response', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_index(op.f('ix_monday_address_raw'), 'address', ['raw'], unique=True, schema='monday')
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('record_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('licensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_index('ix_monday_licensor_name_country_state_city', 'licensor', ['name', 'country', 'state', 'city'], unique=True, schema='monday')
    op.create_table('modality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('orientation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('npa', sa.Integer(), nullable=False),
    sa.Column('nxx', sa.Integer(), nullable=False),
    sa.Column('xxxx', sa.Integer(), nullable=False),
    sa.Column('extension', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_index('ix_monday_phone_npa_nxx_xxxx_extension', 'phone', ['npa', 'nxx', 'xxxx', 'extension'], unique=True, schema='monday')
    op.create_index('ix_monday_phone_npa_nxx_xxxx_null', 'phone', ['npa', 'nxx', 'xxxx'], unique=True, schema='monday', postgresql_where=sa.text('extension IS NULL'))
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('minimum_fee', sa.Integer(), nullable=True),
    sa.Column('maximum_fee', sa.Integer(), nullable=True),
    sa.Column('sliding_scale', sa.Boolean(), nullable=True),
    sa.Column('free_consultation', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=True),
    sa.Column('began_practice', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=1024), nullable=True),
    sa.Column('year_graduated', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('works_with_ages', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.DateTime(), nullable=True),
    sa.Column('licensor_id', sa.Integer(), nullable=False),
    sa.Column('licensee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licensee_id'], ['monday.provider.id'], ),
    sa.ForeignKeyConstraint(['licensor_id'], ['monday.licensor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_index('ix_monday_license_number_licensor_id_licensee_id', 'license', ['number', 'licensor_id', 'licensee_id'], unique=True, schema='monday')
    op.create_table('phones_addresses',
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['monday.address.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['monday.phone.id'], ),
    sa.UniqueConstraint('phone_id', 'address_id'),
    schema='monday'
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('record_limit', sa.Integer(), nullable=True),
    sa.Column('original_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['payor_id'], ['monday.payor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('providers_addresses',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['monday.address.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'address_id'),
    schema='monday'
    )
    op.create_table('providers_credentials',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['monday.credential.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'credential_id'),
    schema='monday'
    )
    op.create_table('providers_groups',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['monday.group.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'group_id'),
    schema='monday'
    )
    op.create_table('providers_languages',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['monday.language.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'language_id'),
    schema='monday'
    )
    op.create_table('providers_modalities',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['monday.modality.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'modality_id'),
    schema='monday'
    )
    op.create_table('providers_orientations',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('orientation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orientation_id'], ['monday.orientation.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'orientation_id'),
    schema='monday'
    )
    op.create_table('providers_payment_methods',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['monday.payment_method.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'payment_method_id'),
    schema='monday'
    )
    op.create_table('providers_payors',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payor_id'], ['monday.payor.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'payor_id'),
    schema='monday'
    )
    op.create_table('providers_phones',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['monday.phone.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'phone_id'),
    schema='monday'
    )
    op.create_table('providers_specialties',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['monday.specialty.id'], ),
    sa.UniqueConstraint('provider_id', 'specialty_id'),
    schema='monday'
    )
    op.create_table('providers_plans',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['monday.plan.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'plan_id'),
    schema='monday'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_plans', schema='monday')
    op.drop_table('providers_specialties', schema='monday')
    op.drop_table('providers_phones', schema='monday')
    op.drop_table('providers_payors', schema='monday')
    op.drop_table('providers_payment_methods', schema='monday')
    op.drop_table('providers_orientations', schema='monday')
    op.drop_table('providers_modalities', schema='monday')
    op.drop_table('providers_languages', schema='monday')
    op.drop_table('providers_groups', schema='monday')
    op.drop_table('providers_credentials', schema='monday')
    op.drop_table('providers_addresses', schema='monday')
    op.drop_table('plan', schema='monday')
    op.drop_table('phones_addresses', schema='monday')
    op.drop_index('ix_monday_license_number_licensor_id_licensee_id', table_name='license', schema='monday')
    op.drop_table('license', schema='monday')
    op.drop_table('specialty', schema='monday')
    op.drop_table('provider', schema='monday')
    op.drop_index('ix_monday_phone_npa_nxx_xxxx_null', table_name='phone', schema='monday')
    op.drop_index('ix_monday_phone_npa_nxx_xxxx_extension', table_name='phone', schema='monday')
    op.drop_table('phone', schema='monday')
    op.drop_table('payor', schema='monday')
    op.drop_table('payment_method', schema='monday')
    op.drop_table('orientation', schema='monday')
    op.drop_table('modality', schema='monday')
    op.drop_index('ix_monday_licensor_name_country_state_city', table_name='licensor', schema='monday')
    op.drop_table('licensor', schema='monday')
    op.drop_table('language', schema='monday')
    op.drop_table('group', schema='monday')
    op.drop_table('directory', schema='monday')
    op.drop_table('credential', schema='monday')
    op.drop_index(op.f('ix_monday_address_raw'), table_name='address', schema='monday')
    op.drop_table('address', schema='monday')
    # ### end Alembic commands ###
