"""add mark for gt/pt phone

Revision ID: 4a099379fe64
Revises: 621e57cca198
Create Date: 2018-01-31 22:29:10.175156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a099379fe64'
down_revision = '621e57cca198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('good_therapy', sa.Boolean(), nullable=True), schema='monday')
    op.add_column('phone', sa.Column('psych_today', sa.Boolean(), nullable=True), schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'psych_today', schema='monday')
    op.drop_column('phone', 'good_therapy', schema='monday')
    # ### end Alembic commands ###
