"""initial

Revision ID: 50bba21c3c7e
Revises: 
Create Date: 2017-12-20 15:27:35.625057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bba21c3c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('modality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('orientation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('record_limit', sa.Integer(), nullable=True),
    sa.Column('original_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('minimum_fee', sa.Integer(), nullable=True),
    sa.Column('maximum_fee', sa.Integer(), nullable=True),
    sa.Column('sliding_scale', sa.Boolean(), nullable=True),
    sa.Column('free_consultation', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=True),
    sa.Column('began_practice', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=1024), nullable=True),
    sa.Column('year_graduated', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('works_with_ages', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('providers_credentials',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['monday.credential.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_groups',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['monday.group.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_languages',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['monday.language.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_modalitiess',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['monday.modality.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_orientations',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('orientation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orientation_id'], ['monday.orientation.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_payment_methods',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['monday.payment_method.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_payors',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payor_id'], ['monday.payor.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_plans',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['monday.plan.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_specialtiess',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['monday.specialty.id'], ),
    schema='monday'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_specialtiess', schema='monday')
    op.drop_table('providers_plans', schema='monday')
    op.drop_table('providers_payors', schema='monday')
    op.drop_table('providers_payment_methods', schema='monday')
    op.drop_table('providers_orientations', schema='monday')
    op.drop_table('providers_modalitiess', schema='monday')
    op.drop_table('providers_languages', schema='monday')
    op.drop_table('providers_groups', schema='monday')
    op.drop_table('providers_credentials', schema='monday')
    op.drop_table('specialty', schema='monday')
    op.drop_table('provider', schema='monday')
    op.drop_table('plan', schema='monday')
    op.drop_table('payor', schema='monday')
    op.drop_table('payment_method', schema='monday')
    op.drop_table('orientation', schema='monday')
    op.drop_table('modality', schema='monday')
    op.drop_table('language', schema='monday')
    op.drop_table('group', schema='monday')
    op.drop_table('credential', schema='monday')
    # ### end Alembic commands ###
