"""more specific locale for licensors

Revision ID: 5b8fcc86bd2d
Revises: 36c2147fa772
Create Date: 2017-12-28 13:35:50.686895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8fcc86bd2d'
down_revision = '36c2147fa772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licensor', sa.Column('city', sa.String(length=64), nullable=True), schema='monday')
    op.add_column('licensor', sa.Column('country', sa.String(length=3), nullable=True), schema='monday')
    op.add_column('licensor', sa.Column('state', sa.String(length=2), nullable=True), schema='monday')
    op.drop_column('licensor', 'locale', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licensor', sa.Column('locale', sa.VARCHAR(), autoincrement=False, nullable=True), schema='monday')
    op.drop_column('licensor', 'state', schema='monday')
    op.drop_column('licensor', 'country', schema='monday')
    op.drop_column('licensor', 'city', schema='monday')
    # ### end Alembic commands ###
