"""add zip code

Revision ID: 621e57cca198
Revises: e1594521f24e
Create Date: 2018-01-30 11:25:57.783777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '621e57cca198'
down_revision = 'e1594521f24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('zip_code', sa.Integer(), nullable=True), schema='monday')
    op.create_index(op.f('ix_monday_address_zip_code'), 'address', ['zip_code'], unique=False, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monday_address_zip_code'), table_name='address', schema='monday')
    op.drop_column('address', 'zip_code', schema='monday')
    # ### end Alembic commands ###
