"""turn groups table into full text search w gin

Revision ID: 806f40e45982
Revises: 8f485d9d39c6
Create Date: 2018-01-05 02:12:39.630134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '806f40e45982'
down_revision = '8f485d9d39c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('body', sa.Text(), nullable=False), schema='monday')
    op.add_column('group', sa.Column('tsv', postgresql.TSVECTOR(), nullable=True), schema='monday')
    op.create_index(op.f('ix_monday_group_body'), 'group', ['body'], unique=True, schema='monday')
    op.create_index('ix_monday_group_body_gin', 'group', ['tsv'], unique=False, schema='monday', postgresql_using='gin')
    op.drop_column('group', 'name', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False), schema='monday')
    op.drop_index('ix_monday_group_body_gin', table_name='group', schema='monday')
    op.drop_index(op.f('ix_monday_group_body'), table_name='group', schema='monday')
    op.drop_column('group', 'tsv', schema='monday')
    op.drop_column('group', 'body', schema='monday')
    # ### end Alembic commands ###
