"""remove unnecessary cruft in specialty list

Revision ID: 8417a4723aa1
Revises: cd47b11f10e6
Create Date: 2018-01-03 17:05:21.330134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8417a4723aa1'
down_revision = 'cd47b11f10e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specialty', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=False,
               schema='monday')
    op.drop_column('specialty', 'is_canonical', schema='monday')
    op.drop_column('specialty', 'alias_id', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('alias_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='monday')
    op.add_column('specialty', sa.Column('is_canonical', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='monday')
    op.alter_column('specialty', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='monday')
    # ### end Alembic commands ###
