"""make tsvectors on orientation

Revision ID: 87879c3a40bf
Revises: ac0e9e84590e
Create Date: 2018-01-05 01:25:34.177797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87879c3a40bf'
down_revision = 'ac0e9e84590e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orientation', sa.Column('body', sa.Text(), nullable=False), schema='monday')
    op.add_column('orientation', sa.Column('tsv', postgresql.TSVECTOR(), nullable=True), schema='monday')
    op.create_index('ix_monday_orientation_body', 'orientation', ['tsv'], unique=False, schema='monday', postgresql_using='gin')
    op.drop_column('orientation', 'name', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orientation', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False), schema='monday')
    op.drop_index('ix_monday_orientation_body', table_name='orientation', schema='monday')
    op.drop_column('orientation', 'tsv', schema='monday')
    op.drop_column('orientation', 'body', schema='monday')
    # ### end Alembic commands ###
