"""add unique index on credential acronym

Revision ID: 8918a8f1d3b9
Revises: 1ba18066fafe
Create Date: 2017-12-30 21:04:24.132462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8918a8f1d3b9'
down_revision = '1ba18066fafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_monday_credential_acronym'), 'credential', ['acronym'], unique=True, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monday_credential_acronym'), table_name='credential', schema='monday')
    # ### end Alembic commands ###
