"""add unique constraint to gin

Revision ID: 8f485d9d39c6
Revises: 87879c3a40bf
Create Date: 2018-01-05 01:30:19.703291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f485d9d39c6'
down_revision = '87879c3a40bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_monday_orientation_body_gin', 'orientation', ['tsv'], unique=False, schema='monday', postgresql_using='gin')
    op.drop_index('ix_monday_orientation_body', table_name='orientation', schema='monday')
    op.create_index(op.f('ix_monday_orientation_body'), 'orientation', ['body'], unique=True, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monday_orientation_body'), table_name='orientation', schema='monday')
    op.create_index('ix_monday_orientation_body', 'orientation', ['tsv'], unique=False, schema='monday')
    op.drop_index('ix_monday_orientation_body_gin', table_name='orientation', schema='monday')
    # ### end Alembic commands ###
