"""initial

Revision ID: a8f88ff8ed2a
Revises: 
Create Date: 2017-12-20 17:46:10.615677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f88ff8ed2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address_number', sa.String(length=16), nullable=True),
    sa.Column('address_number_prefix', sa.String(), nullable=True),
    sa.Column('address_number_suffix', sa.String(length=8), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('corner_of', sa.String(), nullable=True),
    sa.Column('intersection_separator', sa.String(length=8), nullable=True),
    sa.Column('landmark_name', sa.String(length=64), nullable=True),
    sa.Column('not_address', sa.String(), nullable=True),
    sa.Column('occupancy_type', sa.String(length=16), nullable=True),
    sa.Column('occupancy_identifier', sa.String(length=32), nullable=True),
    sa.Column('place_name', sa.String(length=64), nullable=True),
    sa.Column('recipient', sa.String(length=128), nullable=True),
    sa.Column('state_name', sa.String(length=32), nullable=True),
    sa.Column('street_name', sa.String(length=64), nullable=True),
    sa.Column('street_name_pre_directional', sa.String(length=16), nullable=True),
    sa.Column('street_name_pre_modifier', sa.String(length=8), nullable=True),
    sa.Column('street_name_pre_type', sa.String(length=16), nullable=True),
    sa.Column('street_name_post_directional', sa.String(length=16), nullable=True),
    sa.Column('street_name_post_modifier', sa.String(length=8), nullable=True),
    sa.Column('street_name_post_type', sa.String(length=32), nullable=True),
    sa.Column('subaddress_identifier', sa.String(length=16), nullable=True),
    sa.Column('subaddress_type', sa.String(length=16), nullable=True),
    sa.Column('usps_box_group_id', sa.String(), nullable=True),
    sa.Column('usps_box_group_type', sa.String(), nullable=True),
    sa.Column('usps_box_id', sa.String(length=8), nullable=True),
    sa.Column('usps_box_type', sa.String(length=8), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('zip_code_plus_four', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('modality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('orientation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('payor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('record_limit', sa.Integer(), nullable=True),
    sa.Column('original_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('minimum_fee', sa.Integer(), nullable=True),
    sa.Column('maximum_fee', sa.Integer(), nullable=True),
    sa.Column('sliding_scale', sa.Boolean(), nullable=True),
    sa.Column('free_consultation', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=True),
    sa.Column('began_practice', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=1024), nullable=True),
    sa.Column('year_graduated', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('works_with_ages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['monday.address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('providers_credentials',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['monday.credential.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_groups',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['monday.group.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_languages',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['monday.language.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_modalitiess',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['monday.modality.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_orientations',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('orientation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orientation_id'], ['monday.orientation.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_payment_methods',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['monday.payment_method.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_payors',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('payor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payor_id'], ['monday.payor.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_plans',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['monday.plan.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    schema='monday'
    )
    op.create_table('providers_specialtiess',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['monday.specialty.id'], ),
    schema='monday'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_specialtiess', schema='monday')
    op.drop_table('providers_plans', schema='monday')
    op.drop_table('providers_payors', schema='monday')
    op.drop_table('providers_payment_methods', schema='monday')
    op.drop_table('providers_orientations', schema='monday')
    op.drop_table('providers_modalitiess', schema='monday')
    op.drop_table('providers_languages', schema='monday')
    op.drop_table('providers_groups', schema='monday')
    op.drop_table('providers_credentials', schema='monday')
    op.drop_table('provider', schema='monday')
    op.drop_table('specialty', schema='monday')
    op.drop_table('plan', schema='monday')
    op.drop_table('payor', schema='monday')
    op.drop_table('payment_method', schema='monday')
    op.drop_table('orientation', schema='monday')
    op.drop_table('modality', schema='monday')
    op.drop_table('language', schema='monday')
    op.drop_table('group', schema='monday')
    op.drop_table('credential', schema='monday')
    op.drop_table('address', schema='monday')
    # ### end Alembic commands ###
