"""relax the license unique constraint

Revision ID: ae597ce87450
Revises: 07b212a73a3f
Create Date: 2018-02-06 23:31:06.113678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae597ce87450'
down_revision = '07b212a73a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('license_number_licensor_id_licensee_id_key', 'license', schema='monday', type_='unique')
    op.create_unique_constraint(None, 'license', ['number', 'secondary_number', 'licensor_id', 'licensee_id'], schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'license', schema='monday', type_='unique')
    op.create_unique_constraint('license_number_licensor_id_licensee_id_key', 'license', ['number', 'licensor_id', 'licensee_id'], schema='monday')
    # ### end Alembic commands ###
