"""add text search table for accepted payor comments

Revision ID: af6f8d819b86
Revises: 806f40e45982
Create Date: 2018-01-05 13:22:31.264130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af6f8d819b86'
down_revision = '806f40e45982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptedpayorcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_index(op.f('ix_monday_acceptedpayorcomment_body'), 'acceptedpayorcomment', ['body'], unique=True, schema='monday')
    op.create_index('ix_monday_acceptedpayorcomment_body_gin', 'acceptedpayorcomment', ['tsv'], unique=False, schema='monday', postgresql_using='gin')
    op.create_table('providers_acceptedpayorcomments',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('acceptedpayorcomment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acceptedpayorcomment_id'], ['monday.acceptedpayorcomment.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], ),
    sa.UniqueConstraint('provider_id', 'acceptedpayorcomment_id'),
    schema='monday'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_acceptedpayorcomments', schema='monday')
    op.drop_index('ix_monday_acceptedpayorcomment_body_gin', table_name='acceptedpayorcomment', schema='monday')
    op.drop_index(op.f('ix_monday_acceptedpayorcomment_body'), table_name='acceptedpayorcomment', schema='monday')
    op.drop_table('acceptedpayorcomment', schema='monday')
    # ### end Alembic commands ###
