"""remove payor <-> provider join table

Revision ID: ba3bae2b5e27
Revises: af6f8d819b86
Create Date: 2018-01-05 14:01:10.100376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3bae2b5e27'
down_revision = 'af6f8d819b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_payors', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers_payors',
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payor_id'], ['monday.payor.id'], name='providers_payors_payor_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['monday.provider.id'], name='providers_payors_provider_id_fkey'),
    sa.UniqueConstraint('provider_id', 'payor_id', name='providers_payors_provider_id_payor_id_key'),
    schema='monday'
    )
    # ### end Alembic commands ###
