"""add iso codes and indicies to language

Revision ID: caf530452432
Revises: 8417a4723aa1
Create Date: 2018-01-04 13:14:06.434171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf530452432'
down_revision = '8417a4723aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('iso', sa.String(length=3), nullable=False), schema='monday')
    op.create_index(op.f('ix_monday_language_iso'), 'language', ['iso'], unique=True, schema='monday')
    op.create_index(op.f('ix_monday_language_name'), 'language', ['name'], unique=True, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monday_language_name'), table_name='language', schema='monday')
    op.drop_index(op.f('ix_monday_language_iso'), table_name='language', schema='monday')
    op.drop_column('language', 'iso', schema='monday')
    # ### end Alembic commands ###
