"""remove text field

Revision ID: cb06739ca641
Revises: e23dda437192
Create Date: 2018-01-06 15:39:32.754531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb06739ca641'
down_revision = 'e23dda437192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'works_with_ages', schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('works_with_ages', sa.TEXT(), autoincrement=False, nullable=True), schema='monday')
    # ### end Alembic commands ###
