"""add geometry to address

Revision ID: e1594521f24e
Revises: 1cf2ee2dd2b0
Create Date: 2018-01-24 22:10:10.069020

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1594521f24e'
down_revision = '1cf2ee2dd2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('formatted', sa.String(), nullable=True), schema='monday')
    op.add_column('address', sa.Column('formatted_tsv', postgresql.TSVECTOR(), nullable=True), schema='monday')
    op.add_column('address', sa.Column('point', ga.types.Geometry(), nullable=True), schema='monday')
    op.create_index(op.f('ix_monday_address_formatted'), 'address', ['formatted'], unique=False, schema='monday')
    op.create_index('ix_monday_address_formatted_gin', 'address', ['formatted_tsv'], unique=False, schema='monday', postgresql_using='gin')
    op.create_index('ix_monday_address_point_gist', 'address', ['point'], unique=False, schema='monday', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monday_address_point_gist', table_name='address', schema='monday')
    op.drop_index('ix_monday_address_formatted_gin', table_name='address', schema='monday')
    op.drop_index(op.f('ix_monday_address_formatted'), table_name='address', schema='monday')
    op.drop_column('address', 'point', schema='monday')
    op.drop_column('address', 'formatted_tsv', schema='monday')
    op.drop_column('address', 'formatted', schema='monday')
    # ### end Alembic commands ###
