"""add arrays for age groups

Revision ID: e23dda437192
Revises: 3cccf6a0af7d
Create Date: 2018-01-05 16:03:57.591148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e23dda437192'
down_revision = '3cccf6a0af7d'
branch_labels = None
depends_on = None

age_enum = postgresql.ENUM('children', 'teens', 'adults', 'elders', name='age_range_names')


def upgrade():
    age_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('age_groups', postgresql.ARRAY(age_enum), nullable=True), schema='monday')
    op.add_column('provider', sa.Column('age_ranges', postgresql.ARRAY(postgresql.INT4RANGE(), dimensions=1), nullable=True), schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'age_ranges', schema='monday')
    op.drop_column('provider', 'age_groups', schema='monday')
    # ### end Alembic commands ###

    age_enum.drop(op.get_bind(), checkfirst=False)
