"""add license

Revision ID: e5407a162bad
Revises: 4f490ca63763
Create Date: 2017-12-21 16:38:43.264364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5407a162bad'
down_revision = '4f490ca63763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='monday'
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.DateTime(), nullable=True),
    sa.Column('licensor_id', sa.Integer(), nullable=False),
    sa.Column('licensee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licensee_id'], ['monday.provider.id'], ),
    sa.ForeignKeyConstraint(['licensor_id'], ['monday.licensor.id'], ),
    sa.PrimaryKeyConstraint('id', 'licensor_id', 'licensee_id'),
    schema='monday'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license', schema='monday')
    op.drop_table('licensor', schema='monday')
    # ### end Alembic commands ###
