"""index on licensors

Revision ID: eda96eabf504
Revises: 5b8fcc86bd2d
Create Date: 2017-12-28 13:39:18.721053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda96eabf504'
down_revision = '5b8fcc86bd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licensor', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               schema='monday')
    op.create_index('ix_monday_licensor_name_country_state_city', 'licensor', ['name', 'country', 'state', 'city'], unique=True, schema='monday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monday_licensor_name_country_state_city', table_name='licensor', schema='monday')
    op.alter_column('licensor', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               schema='monday')
    # ### end Alembic commands ###
