"""
A list of common therapy credentials from
https://www.networktherapy.com/directory/credentials.asp
"""

from typing import Mapping

CREDENTIAL_ACRONYMS: Mapping[str, str] = {
    'ATR': 'Registered Art Therapist',
    'ATR-BC': 'Registered Art Therapist - Board Certified',
    'BCBA': 'Board Certified Behavior Analyst',
    'BCBT': 'Board Certification in Bereavement Trauma',
    'BCD': 'Board Certified Diplomate in Clinical Social Work',
    'BCDT': 'Board Certification in Disability Trauma',
    'BCDV': 'Board Certification in Domestic Violence',
    'BCETS': 'Board Certified Expert in Traumatic Stress',
    'BCFT': 'Board Certification in Forensic Traumatology',
    'BCIT': 'Board Certification in Illness Trauma',
    'BCMVT': 'Board Certification in Motor Vehicle Trauma',
    'BCPM': 'Board Certification in Pain Management',
    'BCRT': 'Board Certification in Rape Trauma',
    'BCSA': 'Board Certification in Sexual Abuse',
    'BCSCR': 'Board Certification in School Crisis Response',
    'BCSM': 'Board Certification in Stress Management',
    'BCUCR': 'Board Certification in University Crisis Response',
    'CADAC': 'Certified Alcohol and Drug Abuse Counselor',
    'CADC': 'Certified Alcohol and Drug Counselor',
    'CAMF': 'Certified Anger Management Facilitator',
    'CAP': 'Certified Addictions Professional',
    'CART': 'Certified Anger Resolution Therapist',
    'CAS': 'Certified Addiction Specialist',
    'CASAC': 'Credentialed Alcohol and Substance Abuse Counselor',
    'CASAC-T': 'Credentialed Alcohol and Substance Abuse Counselor Trainee',
    'CASAC-G': 'Credentialed Alcohol and Substance Abuse Counselor—Gambling',
    'CBT': 'Certified Bioenergetic Therapist',
    'CCADC': 'Certified Clinical Alcohol and Drug Counselor',
    'CCDP': 'Certified Chemical Dependency Professional',
    'CCHT': 'Certified Clinical Hypnotherapist',
    'CCPT': 'Certified Clinical Pastoral Therapist',
    'CCMH': 'Clinical Counselor in Mental Health',
    'CMHC': 'Certified Mental Health Counselor',
    'CCMHC': 'Certified Clinical Mental Health Counselor',
    'CCSW': 'Certified Clinical Social Worker',
    'CEAP': 'Certified Employee Assistance Professional',
    'CEDS': 'Certified Eating Disorders Specialist',
    'CFLE': 'Certified Family Life Educator',
    'CGP': 'Certified Group Psychotherapist',
    'CHT': 'Certified Hypnotherapist',
    'CICSW': 'Certified Independent Clinical Social Worker',
    'CISW': 'Certified Independent Social Worker',
    'CMFT': 'Certified Marriage and Family Therapist',
    'CpastC': 'Certified Pastoral Counselor',
    'CPC': 'Certified Professional Counselor',
    'CRADC': 'Certified Reciprocal Alcohol and Drug Counselor',
    'CRC': 'Certified Rehabilitation Counselor',
    'CSAC': 'Certified Substance Abuse Counselor',
    'CSW-C': 'Certified Social Worker - Clinical',
    'DAPA': 'Diplomate, American Psychotherapy Association',
    'DCSW': 'Diplomate in Clinical Social Work',
    'DOT SAP': 'Department of Transportation Substance Abuse Professional',
    'DTR': 'Dance Therapist Registered',
    'LAC': 'Licensed Associate Counselor',
    'LADAC': 'Licensed Alcohol and Drug Abuse Counselor',
    'LADC': 'Licensed Alcohol and Drug Counselor',
    'LAMFT': 'Licensed Associate Marriage and Family Therapist',
    'LAPC': 'Licensed Associate Professional Counselor',
    'LASAC': 'Licensed Associate Substance Abuse Counselor',
    'LCADC': 'Licensed Clinical Alcohol and Drug Counselor',
    'LCAS': 'Licensed Clinical Addictions Specialist',
    'LCAT': 'Licensed Creative Arts Therapist',
    'LCDC': 'Licensed Chemical Dependency Counselor',
    'LCDP': 'Licensed Chemical Dependency Professional',
    'LCMFT': 'Licensed Clinical Marriage and Family Therapist',
    'LCMHC': 'Licensed Clinical Mental Health Counselor',
    'LCPC': 'Licensed Clinical Professional Counselor',
    'LCSW': 'Licensed Clinical Social Worker',
    'LCSW-C': 'Licensed Certified Social Worker-Clinical',
    'LCSW-R': 'Licensed Certified Social Worker-Psychotherapy "R" Privilege',
    'LGSW': 'Licensed Graduate Social Worker',
    'LICSW': 'Licensed Independent Clinical Social Worker',
    'LIMFT': 'Licensed Independent Marriage and Family Therapist',
    'LISW': 'Licensed Independent Social Worker',
    'LISW-CP': 'Licensed Independent Social Worker - Clinical Practice',
    'LLP': 'Limited Licensed Psychologist',
    'LMFT': 'Licensed Marriage and Family Therapist',
    'LMHC': 'Licensed Mental Health Counselor',
    'LMHP': 'Licensed Mental Health Practitioner',
    'LMSW': 'Licensed Master Social Worker',
    'LMSW-ACP': 'Licensed Master Social Worker - Advanced Clinical '
                'Practitioner',
    'LPA': 'Licensed Psychological Associate',
    'LpastC': 'Licensed Pastoral Counselor',
    'LPC': 'Licensed Professional Counselor',
    'LPCC': 'Licensed Professional Clinical Counselor',
    'LPCMH': 'Licensed Professional Counselor of Mental Health',
    'LPE': 'Licensed Psychological Examiner',
    'LPP': 'Licensed Pastoral Psychotherapist',
    'LSATP': 'Licensed Substance Abuse Treatment Practitioner',
    'LSCSW': 'Licensed Specialist Clinical Social Worker',
    'LSP': 'Licensed School Psychologist',
    'LSW': 'Licensed Social Worker',
    'MAC': 'Master Addiction Counselor',
    'MFCC': 'Marriage, Family and Child Counselor',
    'MFT': 'Marriage and Family Therapist',
    'MT-BC': 'Music Therapist - Board Certified',
    'NBCCH': 'National Board Certified Clinical Hypnotherapist',
    'NBCDCH': 'National Board Certified Diplomate in Clinical Hypnotherapy',
    'NCC': 'National Certified Counselor',
    'NCPsyA': 'Nationally Certified Psychoanalyst',
    'NCSC': 'National Certified School Counselor',
    'PA': 'Psychological Associate',
    'PLMHP': 'Provisionally Licensed Mental Health Practitioner',
    'PLPC': 'Provisional Licensed Professional Counselor',
    'PMHNP': 'Psychiatric Mental Health Nurse Practitioner',
    'RAS': 'Registered Addiction Specialist',
    'RDT': 'Registered Drama Therapist',
    'REAT': 'Registered Expressive Arts Therapist',
    'RN': 'Registered Nurse',
    'RPC': 'Registered Professional Counselor',
    'RPT': 'Registered Play Therapist',
    'RPT-S': 'Registered Play Therapist-Supervisor',
    'SAP': 'Substance Abuse Professional',
    'SW': 'Social Worker',
    'TLLP': 'Temporary Limited License Psychologist',
    'NP': 'Nurse Practitioner',
    'ACSW': 'Academy of Certified Social Workers',
    'ABPP': 'American Board of Professional Psychology',
    'FIPA': 'Fellow of the International Psychoanalytic Association',
    'RYT': 'Registered Yoga Teacher',
    'CAC': 'Certified Addictions/Alcoholism Counselor',
    'LCP': 'Licensed Clinical Psychologist',
    'CST': 'Certified Sex Therapist',
    'CNP': 'Certified Nonprofit Professional',
    'FAPA': 'Fellow of the American Psychiatric Association',
    'APRN': 'Advanced Practice Registered Nurse',
    'APN': 'Advanced Practice Nurse',
    'BC-DMT': 'Board Certified Dance/Movement Therapist',
    'DCC': 'Distance Credentialed Counselor',
    'SIFI': 'Certification from a Seminar in Field Instruction',
    'LMT': 'Licensed Massage Therapist',
    'ABPN': 'American Board of Psychiatry and Neurology',
    'LBA': 'Licensed Behavior Analyst',
    'CCLS': 'Certified Child Life Specialist',
    'NPP': 'Nurse Practitioner, Psychiatric',
    'BCB': 'Board Certified in Biofeedback',
    'BCN': 'Board Certified in Neurofeedback',
    'BCB-PMD': 'Board Certified in Pelvic Muscle Dysfunction Biofeedback',
    'QCSW': 'Qualified Clinical Social Worker',
    'ABSNP': 'Diplomate in School Neuropsychology',
    'ESQ': 'Board Certified Lawyer',
    'ICADC': 'Internationally Certified Alcohol & Drug Counselor',
    'ICAADC': 'Internationally Certified Advanced Alcohol & Drug Counselor',
    'ICCS': 'Internationally Certified Clinical Supervisor',
    'ICCJP': 'Internationally Certified Criminal Justice Addictions '
             'Professional',
    'ICPS': 'Internationally Certified Prevention Specialist ',
    'ICPR': 'Internationally Certified Peer Recovery',
    'RD': 'Registered Dietitian',
    'CHC': 'Certificate in Healthcare Compliance',
    'BCC': 'Board Certified Coach',
    'OTR': 'Registered Occupational Therapist',
    'OTL': 'Licensed Occupational Therapist',
    'CH': 'Clinical Hypnotherapist',
    'BCH': 'Board Certified Hypnotherapist',
    'EDS': 'Post-graduate Specialist in Education',
    'FAACP': 'Fellow of the American Academy of Clinical Psychology',
    'FT': 'Fellow in Thanatology',
    'CPCC': 'Certified Professional Career Coach',
    'MCC': 'Master Career Counselor',
    'CCTP': 'Certified Clinical Trauma Professional',
    'CCBT': 'Certified Cognitive-Behavioral Therapist',
    'CAADC': 'Certified Advanced Alcohol and Drug Counselor',
    'CSAT': 'Certified Sex Addiction Therapist',
    'CSAT-C': 'Certified Sex Addiction Therapist Candidate',
    'CSAT-S': 'Certified Sex Addiction Therapist Supervisor',
    'LPsyA': 'Licensed Psychoanalyst',
    'CLC': 'Certified Lactation Counselor',
    'FAGPA': 'Fellow of the American Group Psychotherapy Association',
    'ACS': 'Approved Clinical Supervisor',
    'CCS': 'Certified Coding Specialist',
    'CCS-P': 'Physician-based Certified Coding Specialist',
    'CNS': 'Certified Nutrition Specialist',

}
